### ISSUE TITLE
不能生成framework

### ISSUE THREAD

**Issue by wushi333333** [leancloud/leancloud-social-ios#13]
很多用户都是用win开发，偶尔用下xcode,这sdk还得要求用户安装cocospod才能运行demo，好不容易运行起，demo后，在游戏中还运行不起，直接生成framework，编译出来又是空得，让用户如何操作，简直太垃圾了吧

**Comment by tang3w** [comment]
我们支持 CocoaPods 是为了更方便用户集成。除此之外，项目本身是开源的，您可以自行打包，也可以源码集成，我们提供了最大的自由度让您选择您认为最方便的方式进行集成。可能是集成的方式有些问题，但是抱歉，我们暂时不提供上门技术支持。

**Comment by wushi333333** [comment]
那为什么不能直接生成一个framework 让用户下载来用就可以了？？？

**Comment by lzwjava** [comment]
@wushi333333 https://github.com/leancloud/leancloud-social-ios/pull/15 按照我们这里的截图，设置一下应该可以解决。问题比较奇怪。

选中 framework Target ，然后点击 Build 下的 Archive 来生成 framework。

**Comment by wushi333333** [comment]
谢谢哈，我说下我的流程，首先从服务期下载源码：
![1](https://cloud.githubusercontent.com/assets/1525726/10067149/6b7b9bd0-62cc-11e5-81fe-4f15f95ff46d.jpg)
然后再
![2](https://cloud.githubusercontent.com/assets/1525726/10067161/83c0371e-62cc-11e5-851a-f4bf7a900d4c.jpg)
![3](https://cloud.githubusercontent.com/assets/1525726/10067182/bf8201f6-62cc-11e5-8fbd-d39ab2225205.jpg)
然后demo就可以运行了，打开后，在 Xcode 中选择 UniversalFramework Target，设备选为 iOS Device，在 Product 菜单中选择 Archive 即可开始编译。
![4](https://cloud.githubusercontent.com/assets/1525726/10067231/46dcb312-62cd-11e5-9c07-7d0742c8a75b.jpg)
编译提示成功，但是有这些错误

**Comment by lzwjava** [comment]
@jwfing @tang3w Universal Framework Target 的用意何在？直接选择 LeanCloudSocial 的 framework 来 archive 也行吧。

了解到似乎 UniversalFramework Target 是 Xcode 6 前编译 framework 的一个方法。Xcode 6 开始已经自带了 Build Tools ，现在似乎不需要了。

**Comment by lzwjava** [comment]
@wushi333333 选择 LeanCloudSocial Target ，而不是 UniversalFramework，来 archive 试试

**Comment by wushi333333** [comment]
这个是需要开发证书才能打，我电脑上没有，要用其他电脑才行

**Comment by wushi333333** [comment]
所以我说自己生成framework很麻烦拉
![5](https://cloud.githubusercontent.com/assets/1525726/10068247/6f6dc8c2-62d5-11e5-8fa0-e2affd04349b.jpg)

**Comment by lzwjava** [comment]
![image](https://cloud.githubusercontent.com/assets/5022872/10068695/f7e8cb0e-62d8-11e5-9a90-986095d23fc3.png)

设置成这样

**Comment by wushi333333** [comment]
问题是这里
![6](https://cloud.githubusercontent.com/assets/1525726/10070703/c9c87c98-62e6-11e5-869d-990f85e17196.jpg)
