### ISSUE TITLE
Archive编译报错。

### ISSUE THREAD

**Issue by gitcalmlyhub** [leancloud/leancloud-social-ios#16]
在 Xcode 中选择 UniversalFramework Target，设备选为 iOS Device，然后在 Product 菜单中选择 Archive 开始编译，会提示编译成功，但是会出现如下三个错误。
使用的是Xcode7 + iOS9 SDK.
![default](https://cloud.githubusercontent.com/assets/12692156/10095348/af012044-639b-11e5-960d-df7c71be43a7.PNG)

**Comment by lzwjava** [comment]
直接选择 LeanCloudSocial Target 来 archive 吧

**Comment by lzwjava** [comment]
现在试试？之前我们编译脚本有些错误
