### ISSUE TITLE
deleteAuthDataForPlatform 方法名称需要更新，需要与 addAuthorData:platform 保持统一

### ISSUE THREAD

**Issue by myleslee** [leancloud/leancloud-social-ios#23]
位置：
leancloud-social-ios/Classes/AVUser+SNS.m
leancloud-social-ios/Classes/AVUser+SNS.h

文档中也不一致：

<img width="652" alt="a" src="https://cloud.githubusercontent.com/assets/108758/10992511/6dea6724-84a1-11e5-9e88-bdefc525f7c2.png">

**Comment by lzwjava** [comment]
文档里改成 deleteAuthDataForPlatform 就行了。

因为添加的时候，platform 和 authData 都需要知道。删除的时候，只需知道 platfrom 就行了。
