### ISSUE TITLE
多个方法中 Manualy 拼写错误

### ISSUE THREAD

**Issue by myleslee** [leancloud/leancloud-social-ios#24]
Manualy > Manually 
双写 L。

- `loginManualyWithURL:`
- `loginManualyWithCallback:`

位于：
- Classes/AVOSCloudSNS.m
- Classes/AVOSCloudSNS.h

**Comment by hjiang** [comment]
可以增加一个正确拼写的方法，把老的方法 deprecate (编译时警告)。

**Comment by lzwjava** [comment]
https://github.com/leancloud/leancloud-social-ios/pull/25
