### ISSUE TITLE
"open LeanCloudSocialDemo.xcworkspace" 是否应为 "open LeanCloudSocial.xcworkspace" ?

### ISSUE THREAD

**Issue by dfi** [leancloud/leancloud-social-ios#29]

**Comment by lzwjava** [comment]
PR is welcome! 

:dancers:

**Comment by ChenYilong** [comment]
已经更正，见https://github.com/leancloud/leancloud-social-ios/commit/c7905a32c219247f4de1c450aeb39e5d59d2ed59
