### ISSUE TITLE
LeanCloudSocialDynamic下AVUser+SNS.h出錯

### ISSUE THREAD

**Issue by ustbenchan** [leancloud/leancloud-social-ios#32]
/Pods/LeanCloudSocialDynamic/Classes/AVUser+SNS.h:12:9: 
Include of non-modular header inside framework module 'LeanCloudSocialDynamic.AVUser_SNS'

將AVUser+SNS.h 的line 12
```objective-c
#import <AVOSCloud/AVUser.h>
```
改為
```objective-c
@import AVOSCloud;
```
才能成功

請修正

**Comment by ChenYilong** [comment]
已更正 https://github.com/leancloud/leancloud-social-ios/pull/34

**Comment by ustbenchan** [comment]
改完後能不能更一下 LeanCloudSocialDynamic.podspec阿?

Could you please update the LeanCloudSocialDynamic.podspec for the new version as well?

Thank you very much.
