### ISSUE TITLE
pod安装好之后 无法import，请问这个库还有在维护吗？

### ISSUE THREAD

**Issue by senseluo** [leancloud/leancloud-social-ios#35]
pod 'LeanCloudSocialDynamic' 
swift桥接之后没法桥接，提示找不到头文件
打不出AVOSCloudSNS
如果是 pod 'LeanCloudSocial'就行

**Comment by ChenYilong** [comment]
动态库现在确实有点问题，后续会更新下。可暂时先使用静态库。等待后续更新好动态库再来使用。

**Comment by chuyik** [comment]
@ChenYilong 请问能更新下动态库吗？

**Comment by ChenYilong** [comment]
已经以源码方式发布，请使用如下方式进行导入：

> pod 'LeanCloudSocial'
