### ISSUE TITLE
The 'Pods' target has transitive dependencies that include static binaries

### ISSUE THREAD

**Issue by wao813** [leancloud/leancloud-social-ios#37]
在Swift project 里的Podfile使用 `use_frameworks!` ，在`pod install`的时候会出现错误：
[!] The 'Pods' target has transitive dependencies that include static binaries: AVOSCloud.framework and AVOSCloudIM.framework

**Comment by Smiacter** [comment]
我和一楼遇到类似的问题，首先用pod导入的三个基础库，然后pod 'LeanCloudSocial'，出现[!] The 'Pods' target has transitive dependencies that include static binaries: (.../Pods/AVOSCloud/libAVOSCloud.a)

**Comment by ustbenchan** [comment]
`use_frameworks!` 是要搭上用 `dynamic` 的pod才可以

```
use_frameworks!

pod 'AVOSCloudDynamic', '~> 3.2.4'
pod 'AVOSCloudCrashReportingDynamic', '~> 3.2.4'
pod 'LeanCloudSocialDynamic', '0.0.9'
```

类似这样
另外 作为用户我还是建议你们到
[forum.leancloud.cn](forum.leancloud.cn)
提问吧 那边比较有人气

**Comment by wao813** [comment]
@ustbenchan 谢谢！
