### ISSUE TITLE
AFNetworking Issue

### ISSUE THREAD

**Issue by helloworlderly** [leancloud/leancloud-social-ios#48]
我要引入你们的Social库，然后cocoapods安装，引入库时候需要依赖AFNetworking，你们用的是1.0版本，而我其他的库依赖AFNetworking都是3.0以上，请更新AFNetworking

**Comment by isaced** [comment]
参见 #39 有临时解决方案，不过是希望官方早点解决这个问题。🙏🏻

**Comment by ChenYilong** [comment]
1.0.0-beta 已经发布，相关PR见：https://github.com/leancloud/leancloud-social-ios/pull/53
