### ISSUE TITLE
Swift AVUser 子类化失效

### ISSUE THREAD

**Issue by isaced** [leancloud/leancloud-social-ios#49]
在 `AVUser+SNS.m` 中 `loginWithAuthData:` 方法登录后，使用子类化的 User.current() 还是返回的 AVUser 实体，导致之后任何地方通过子类化 User 取属性直接崩溃。（在OC项目中没有问题）

看了下代码在 `AVSNSHttpClient:postObject` 返回数据后构造 User 并没有调用 `[self userOrSubclassUser]`  来初始化而是调用的 `[self user]`，不知道是不是这里的原因？

**Comment by ChenYilong** [comment]
已经合并，发布了1.0.0-beta2。
