### ISSUE TITLE
AFN依赖冲突

### ISSUE THREAD

**Issue by MichaelJordanYang** [leancloud/leancloud-social-ios#52]
leancloud-social-ios框架很好.感谢,有一点需要更新一下就是AFNetworking需要更新到最新版本3.1.0才行.不然我的项目pod你们的框架会导致afn方法冲突.您框架的afn方法已过期.谢谢

**Comment by ChenYilong** [comment]
1.0.0-beta 已经发布，相关PR见：https://github.com/leancloud/leancloud-social-ios/pull/53
