### ISSUE TITLE
找不到#import "AVObject_Internal.h"咋回事

### ISSUE THREAD

**Issue by ancoo** [leancloud/leancloud-social-ios#54]
pod 也找不到。。

**Comment by ChenYilong** [comment]
这个文件是私有的，是找不到的，你引用他做什么？

**Comment by ancoo** [comment]
@ChenYilong 
AVUser+SNS.m 文件显示找不到#import "AVObject_Internal.h

**Comment by yyyzzq** [comment]
AVUser+SNS.m 中 报错 AVUser_Internal.h‘file not fount

**Comment by ancoo** [comment]
@yyyzzq 
解决方法是重写一份 AVUser_Internal2.h
把AVUser_Internal.h里面的复制一下

**Comment by ChenYilong** [comment]
v1.0.0-beta3 已发布，请更新下，修复了该问题。
